version: '3'
networks:
  social_network:
    driver: bridge

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=AccuKnox
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    networks:
      - social_network
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/code
    networks:
      - social_network
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_NAME=AccuKnox
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=5432